# Generated by Django 2.2.3 on 2019-07-11 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20190711_1234'),
        ('registro_de_hora_extra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_De_Horas_Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=70)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionarios')),
            ],
        ),
        migrations.DeleteModel(
            name='registro_de_hora_extra',
        ),
    ]
