# Generated by Django 2.2.3 on 2019-07-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20190711_1234'),
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='departamentos',
            new_name='departamento',
        ),
    ]
